goods/urls.py
from django.urls import path,re_path,include
import goods.views as views
from django.conf.urls import url
urlpatterns = [
    url('^$',views.index),
    re_path('^index$',views.index,name='index'),

    re_path('^contact$',views.contact_us,name='contact'),

    re_path('^about-us$',views.about_us,name='about-us'),

    url(r'^shop$',views.shop,name='shop'),
    url(r'^shop/(.*)/',views.shop,name='shop-catalog'),

    url(r'^details/(\d+)',views.details,name='details')

]

vivicompany/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.urls import include

urlpatterns = [
    re_path('^',include(('goods.urls','goods'),namespace='goods')),
    path('admin/', admin.site.urls),

]

goods/models.py
from django.db import models

# Create your models here.
from django.db import models

class Goods(models.Model):
    gname = models.CharField(null=False,max_length=256)
    gprice = models.FloatField(null=False,)
    gcatalog = models.CharField(null=True,max_length=256)
    # gsales = models.CharField(null=True,max_length=256)
    gvocation = models.CharField(null=True,max_length=256)
    gshort_details = models.CharField(null=False,max_length=2048)
    glong_details = models.CharField(null=False,max_length=4056)
    gpub_time = models.DateTimeField(auto_now=True,)

    def __str__(self):
        return self.gname

goods/views.py
import os

from django.shortcuts import render
from .models import Goods
# Create your views here.
from vivicompany.settings import *

catalog_list = []
all_catalog = Goods.objects.values('gcatalog').distinct()
for item in all_catalog:
    catalog_list.append(item['gcatalog'])
catalog_list= set(catalog_list)

def index(request):

    context = {
    'catalog':catalog_list
    }
    return render(request, 'index.html', context)


def contact_us(request,):
    context = {
        'name':'Vivi',
        'tel':'18888888888',
        'catalog':catalog_list
    }
    return render(request,'contact.html',context)


def about_us(request,):
    context = {
        'catalog': catalog_list
    }
    return render(request,'about-us.html',context)

#

def shop(request,catalog=''):
    if not catalog :
        goods_list = Goods.objects.all()

    else:
        goods_list = Goods.objects.filter(gcatalog=catalog)

    context = {
        'goods_list':goods_list,
        'catalog': catalog_list
    }
    return render(request,'shop-left-sidebar.html',context)


def details(request,id_get):
    file_list = []
    goods = Goods.objects.filter(id=id_get)[0]
    file_path = os.listdir(os.path.join(BASE_DIR,'static','goods','img','product','thumbnail-size'))
    for name in file_path:
        if name.startswith(goods.gname):
            file_list.append(name)
    context = {
        'goods':goods,
        'file_list':file_list,
        'catalog': catalog_list
    }
    return render(request,'product-details.html',context)

templates/base.html
{% load  static from staticfiles %}

<!doctype html>
<html class="no-js" lang="zxx">


<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>Genrre - Fashion eCommerce Bootstrap4 Template</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Favicon -->
	<link rel="shortcut icon" href="{% static  'goods/img/favicon.ico' %}" type="image/x-icon">
	<link rel="apple-touch-icon" href="{% static 'goods/img/icon.png' %}">

	<!-- Google font (font-family: 'Carrois Gothic', sans-serif;) -->
	<link href="https://fonts.googleapis.com/css?family=Carrois+Gothic" rel="stylesheet">
	<!-- Google font (font-family: 'Open Sans', sans-serif;) -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">

	<!-- Plugins -->
	<link rel="stylesheet" href="{% static 'goods/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'goods/css/plugins.css' %}">

	<!-- Style Css -->
	<link rel="stylesheet" href="/static/goods/css/style.css">

	<!-- Custom Styles -->
	<link rel="stylesheet" href="{% static 'goods/css/custom.css' %}">
</head>

<body>
	<!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->

	<!-- Add your site or application content here -->

	<!-- Wrapper -->
	<div id="wrapper" class="wrapper">

		<!-- Header -->
		<header class="header sticky-header">

			<!-- Header Top Area -->
			<div class="header-top-area">
				<div class="container">
					<div class="row align-items-center">
						<div class="col-lg-6 col-md-6 col-12">
							<form action="#" class="header-top-left">
								<div class="language-selection">
									<label for="language-selection">Language:</label>
									<select name="language-selection" id="language-selection">
										<option value="1">English</option>
{#										<option value="2">Spanish</option>#}
{#										<option value="3">Hindi</option>#}
									</select>
								</div>
								<div class="currency-selection">
									<label for="currency-selection">Currency:</label>
									<select name="currency-selection" id="currency-selection">
										<option value="1">Us Dollor</option>
{#										<option value="2">Singapore Dollor</option>#}
{#										<option value="3">Newzeland Dollor</option>#}
									</select>
								</div>
							</form>
						</div>
						<div class="col-lg-6 col-md-6 col-12">
							<ul class="header-top-right">
{#								<li><a href="my-account.html">My Account</a></li>#}
{#								<li><a href="cart.html">Shopping Cart</a></li>#}
{#								<li><a href="checkout.html">Checkout</a></li>#}
							</ul>
						</div>
					</div>
				</div>
			</div>
			<!--// Header Top Area -->
			<!-- Header Middle Area -->
			<div class="header-middle-area cr-border cr-border-bottom">
				<div class="container">
					<div class="row align-items-center">
						<div class="col-lg-4 col-12">
							<form class="header-search">
								<select name="header-search-categories">
									<option value="1">All Categories</option>

                                    {#this read the catalog from the database automatically so need maintain the database catalog#}
                                    {% for foo in catalog %}
                                        <option value="1">{{ foo }}</option>
                                    {% endfor %}


								</select>
								<input type="text" placeholder="Search product...">
								<button type="submit"><i class="fa fa-search"></i></button>
							</form>
						</div>
						<div class="col-lg-4 col-md-6 col-sm-7 col-12">
							<div class="header-logo">
								<a href="base_back.html">
									<img src="{% static 'goods/img/logo/logo-1.png' %}" alt="logo">
								</a>
							</div>
						</div>

					</div>
				</div>
			</div>
			<!--// Header Middle Area -->

			<!-- Header Bottom Area -->
			<div class="header-bottom-area d-none d-lg-block">
				<div class="container">
					<div class="header-bottom-inner">
						<nav class="sn-navigation">
							<ul>
								<li><a href="{% url 'goods:index'%}">HOME</a></li>
								<li><a href="{% url 'goods:shop' %}">SHOP</a></li>
								<li><a href="{% url 'goods:about-us' %}">ABOUT US</a></li>
								<li><a href="{% url 'goods:contact' %}">CONTACT</a></li>
							</ul>
						</nav>
						<div class="header-bottom-social">
							<span>Follow Us On:</span>
							<ul>
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-rss"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<!--// Header Bottom Area -->

			<!-- Header Mobile Menu -->
			<div class="mobile-menu-area d-block d-lg-none">
				<div class="container">
					<div class="mobile-menu clearfix">
						<div class="header-bottom-social">
							<span>Follow Us On:</span>
							<ul>
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-rss"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<!--// Header Mobile Menu -->

		</header>
		<!--// Header -->

        {% block main_block %}

        {% endblock %}

        <main class="page-content">
			<!-- Features Area -->
			<div class="features-area">
				<div class="container">
					<div class="row justify-content-center features-wrapper">

						<!-- Single Features -->
						<div class="col-lg-4 col-md-6 col-12">
							<div class="features text-center">
								<h6>MONEY BACK GUARANTEED</h6>
								<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur</p>
							</div>
						</div>
						<!--// Single Features -->

						<!-- Single Features -->
						<div class="col-lg-4 col-md-6 col-12">
							<div class="features text-center">
								<h6>FREE WORLDWIDE DELIVERY</h6>
								<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur</p>
							</div>
						</div>
						<!--// Single Features -->

						<!-- Single Features -->
						<div class="col-lg-4 col-md-6 col-12">
							<div class="features text-center">
								<h6>ONLINE SUPPORT 24/7</h6>
								<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur</p>
							</div>
						</div>
						<!--// Single Features -->

					</div>
				</div>
			</div>
			<!--// Features Area -->

			<!-- Newsletter & Brand Logos Area -->
			<div class="newsletter-brandlogo-area section-padding-xs">
				<div class="container">
					<div class="row no-gutters align-items-center">

						<!-- Newsletter -->
						<div class="col-lg-4">
							<div class="newsletterbox">
								<h5>SIGN UP FOR OUR WEEKLY NEWSLETTER !</h5>
								<form action="#">
									<input type="text" placeholder="Email">
									<button type="submit">Subscribe</button>
								</form>
							</div>
						</div>
						<!--// Newsletter -->

						<!-- Brand Logo -->
						<div class="col-lg-8">
							<div class="brand-logos slider-navigation-2">
								<div class="brand-logo">
									<a href="#">
										<img src="/static/goods/img/brand-logos/brand-logo-1.jpg" alt="best brand logo">
									</a>
								</div>
								<div class="brand-logo">
									<a href="#">
										<img src="/static/goods/img/brand-logos/brand-logo-2.jpg" alt="best brand logo">
									</a>
								</div>
								<div class="brand-logo">
									<a href="#">
										<img src="/static/goods/img/brand-logos/brand-logo-3.jpg" alt="best brand logo">
									</a>
								</div>
								<div class="brand-logo">
									<a href="#">
										<img src="/static/goods/img/brand-logos/brand-logo-4.jpg" alt="best brand logo">
									</a>
								</div>
								<div class="brand-logo">
									<a href="#">
										<img src="/static/goods/img/brand-logos/brand-logo-2.jpg" alt="best brand logo">
									</a>
								</div>
								<div class="brand-logo">
									<a href="#">
										<img src="/static/goods/img/brand-logos/brand-logo-3.jpg" alt="best brand logo">
									</a>
								</div>
							</div>
						</div>
						<!--// Brand Logo -->

					</div>
				</div>
			</div>
			<!--// Newsletter & Brand Logos Area -->

		</main>
		<!--// Page Conttent -->

		<!-- Footer Area -->
		<footer class="footer-area bg-black section-padding-sm">

			<!-- Footer Top Area -->
			<div class="footer-top-area">
				<div class="container">
					<div class="row widgets footer-widgets">

						<!-- Single Widget -->
						<div class="col-lg-3 col-md-6 col-sm-6 col-12">
							<div class="single-widget widget-quicklinks">
								<h6 class="widget-title">INFOMATION</h6>
								<ul>
									<li><a href="#">Our Blog</a></li>
									<li><a href="#">About Our Shop</a></li>
									<li><a href="#">Secure Shopping</a></li>
									<li><a href="#">Privacy Policy</a></li>
									<li><a href="#">Delivery infomation</a></li>
									<li><a href="#">Advanced Search</a></li>
								</ul>
							</div>
						</div>
						<!--// Single Widget -->

						<!-- Single Widget -->
						<div class="col-lg-3 col-md-6 col-sm-6 col-12">
							<div class="single-widget widget-quicklinks">
								<h6 class="widget-title">OUR SERVICES</h6>
								<ul>
									<li><a href="#">Order History</a></li>
									<li><a href="#">Shipping & Returns</a></li>
									<li><a href="#">Secure Shopping</a></li>
									<li><a href="#">International Shipping</a></li>
									<li><a href="#">Affiliates</a></li>
									<li><a href="#">Returns</a></li>
								</ul>
							</div>
						</div>
						<!--// Single Widget -->

						<!-- Single Widget -->
						<div class="col-lg-3 col-md-6 col-sm-6 col-12">
							<div class="single-widget widget-quicklinks">
								<h6 class="widget-title">OUR SUPPORT</h6>
								<ul>
									<li><a href="my-account.html">My Account</a></li>
									<li><a href="#">Contact</a></li>
									<li><a href="#">About Us</a></li>
									<li><a href="#">Sample Page</a></li>
									<li><a href="#">My address</a></li>
									<li><a href="#">My credit slips</a></li>
								</ul>
							</div>
						</div>
						<!--// Single Widget -->

						<!-- Single Widget -->
						<div class="col-lg-3 col-md-6 col-sm-6 col-12">
							<div class="single-widget widget-contact">
								<h6 class="widget-title">CONTACT US</h6>
								<ul>
									<li class="location">
										<i class="fa fa-map-marker"></i>
										<p>1234 Heaven Stress, Beverly Hill OldYork UnitedState of Lorem</p>
									</li>
									<li class="phone">
										<i class="fa fa-mobile"></i>
										<a href="tel:+80001234567890">(800) 0123 4567 890</a>
										<a href="tel:+80009876543210">(800) 0987 6543 210</a>
									</li>
									<li class="mail">
										<i class="fa fa-envelope-o"></i>
										<a href="mailto://info1@example.com">info1@example.com</a>
										<a href="mailto://info2@example.com">info2@example.com</a>
									</li>
								</ul>
							</div>
						</div>
						<!--// Single Widget -->

					</div>
				</div>
			</div>
			<!--// Footer Top Area -->

			<!-- Footer Copyright Area -->
			<div class="footer-copyright-area section-padding-top-xs">
				<div class="container">
					<div class="row align-items-center">
						<div class="col-lg-9">
							<p class="footer-copyright">Copyright © 2018 Vivi Company</p>
						</div>
						<div class="col-lg-3">
							<div class="footer-social-links">
								<ul>
									<li><a data-toggle="tooltip" title="Facebook" href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a data-toggle="tooltip" title="Twitter" href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a data-toggle="tooltip" title="Tumblr" href="#"><i class="fa fa-tumblr"></i></a></li>
									<li><a data-toggle="tooltip" title="Google Plus" href="#"><i class="fa fa-google-plus"></i></a></li>
									<li><a data-toggle="tooltip" title="Dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--// Footer Copyright Area -->

		</footer>
		<!--// Footer Area -->


	</div>
	<!--// Wrapper -->

	<!-- Js Files -->
	<script src="{% static 'goods/js/vendor/modernizr-3.6.0.min.js' %}" ></script>
	<script src="{% static 'goods/js/vendor/jquery-3.3.1.min.js' %}" ></script>
	<script src="{% static 'goods/js/popper.min.js' %}" ></script>
	<script src="{% static 'goods/js/bootstrap.min.js' %}" ></script>
	<script src="{% static 'goods/js/plugins.js' %}" ></script>
	<script src="{% static 'goods/js/main.js' %}" ></script>
</body>


<!-- source http://www.scnoob.com More templates http://www.scnoob.com/moban -->
</html>

templates/contact.html
{% extends 'base.html' %}
{% load staticfiles %}


        {% block main_block %}
        <!-- Bradcrumb Area -->
        <div class="sn-breadcrumb-are bg-theme section-padding-xs">
            <div class="container">
                <div class="sn-breadcrumb text-center">
                    <h3>CONTACT US</h3>
                </div>
            </div>
        </div>
        <!--// Bradcrumb Area -->

		<!-- Page Conttent -->
		<main class="page-content">

            <!-- Contact Area -->
            <div class="contact-us-area section-padding-md">

				<!-- Contact Us Info -->
				<div class="container">
					<div class="row">
						
						<div class="col-lg-6">
							<div class="commentbox">
								<h5>LEAVE US A MESSAGE</h5>
								<form id="contact-form" action="mail.php" method="POST" class="sn-form contact-form">
									<div class="sn-form-inner">
										<div class="single-input single-input-half">
											<label for="new-review-name">Name*</label>
											<input type="text" name="name" id="new-review-name">
										</div>
										<div class="single-input single-input-half">
											<label for="new-review-email">Email*</label>
											<input type="email" name="email" id="new-review-email">
										</div>
										<div class="single-input">
											<label for="new-review-subject">Subject*</label>
											<input type="text" name="subject" id="new-review-subject">
										</div>
										<div class="single-input">
											<label for="new-review-textbox">Your Message</label>
											<textarea id="new-review-textbox" name="message" cols="30" rows="5"></textarea>
										</div>
										<div class="single-input">
											<button class="sn-button sn-button-dark" type="submit"><span>Send</span></button>
										</div>
									</div>
								</form>
								<p class="form-message"></p>
							</div>
						</div>

						<div class="col-lg-6">
							<div class="google-map-wrapper">
								<div class="google-map" id="google-map"></div>
							</div>
						</div>

					</div>
				</div>
				<!--// Contact Us Info -->

            </div>
            <!--// Contact Area -->

        </main>
        {% endblock %}

templates/goods/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ViViCompany</title>
</head>
<body>
 this is a test information!
</body>
</html>

templates/info/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ViViCompany</title>
</head>
<body>
 this is a test information!

<a href="">contact us</a>
</body>
</html>

templates/product-details.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main_block %}
		<!-- Page Conttent -->
		<main class="page-content">

            <!-- Product Page Wrapper -->
            <div class="product-page-wrapper section-padding-bottom-md">
                <div class="container">

                    <!-- Shop Breadcrumb -->
                    <div class="shop-breadcrumb">
                        <ul>
                            <li><a href="{% url 'goods:index' %}">Home</a></li>
                            <li><a href="{% url 'goods:shop' %}">Shop</a></li>
                            <li><a href="{% url 'goods:shop' %}">Mens</a></li>
                            <li>Aenean Eu Tristique</li>
                        </ul>
                    </div>
                    <!--// Shop Breadcrumb -->

                    <!-- Product Details Inner -->
                    <div class="product-details">
                        <!-- Product Details Left -->
                        <div class="product-details-left">
                            <div class="product-details-images slider-navigation-2">
                                {% for file in file_list %}
                                <a href="/static/goods/img/product/large-size/{{ file }}">
                                    <img src="/static/goods/img/product/thumbnail-size/{{ file }}" alt="product image">
                                </a>
                                {% endfor %}
                            </div>
{#                            <div class="product-details-thumbs slider-navigation-2">#}
{#                                {% for file in file_list %}#}
{#                                    <img src="/static/goods/img/product/small-size/{{ file }}" alt="product image thumb">#}
{#                                {% endfor %}#}
{#                            </div>#}
                        </div>
                        <!--// Product Details Left -->

                        <!-- Product Details Right -->
                        <div class="product-details-right">
                            <h5 class="product-title">Aenean Eu Tristique</h5>

                            <div class="ratting-stock-availbility">
                                <div class="ratting-box">
                                    <span class="active"><i class="fa fa-star"></i></span>
                                    <span class="active"><i class="fa fa-star"></i></span>
                                    <span class="active"><i class="fa fa-star"></i></span>
                                    <span class="active"><i class="fa fa-star"></i></span>
                                    <span><i class="fa fa-star"></i></span>
                                </div>
                                <span class="stock-available">In stock</span>
                            </div>

                            <p>{{ goods.gshort_details }} </p>

                            <div class="price-box">
                                <span class="pricebox-price">{{ goods.gprice }}</span>
                            </div>
{##}
{#                            <div class="product-details-quantity">#}
{#                                <div class="quantity-select">#}
{#                                    <input type="text" value="1">#}
{#                                </div>#}
{#                                <a href="#" class="add-to-cart-button">#}
{#                                    <span>ADD TO CART</span>#}
{#                                </a>#}
{#                            </div>#}

{#                            <div class="product-details-color">#}
{#                                <span>Color :</span>#}
{#                                <ul>#}
{#                                    <li class="red"><span></span></li>#}
{#                                    <li class="green checked"><span></span></li>#}
{#                                    <li class="blue"><span></span></li>#}
{#                                    <li class="black"><span></span></li>#}
{#                                </ul>#}
{#                            </div>#}
{##}
{#                            <div class="product-details-size">#}
{#                                <span>Size :</span>#}
{#                                <ul>#}
{#                                    <li class="checked"><span>S</span></li>#}
{#                                    <li><span>M</span></li>#}
{#                                    <li><span>L</span></li>#}
{#                                    <li><span>XL</span></li>#}
{#                                    <li><span>XXL</span></li>#}
{#                                </ul>#}
{#                            </div>#}

                            <div class="product-details-categories">
                                <span>Categories :</span>
                                <ul>
                                    <li><a href="#">{{ goods.gcatalog }}</a></li>

                                </ul>
                            </div>
{##}
{#                            <div class="product-details-tags">#}
{#                                <span>Tags :</span>#}
{#                                <ul>#}
{#                                    <li><a href="shop.html">Electronic</a></li>#}
{#                                    <li><a href="shop.html">Television</a></li>#}
{#                                </ul>#}
{#                            </div>#}

                            <div class="product-details-socialshare">
                                <span>Share :</span>
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <!--// Product Details Right -->

                    </div>
                    <!--// Product Details Inner -->
                    
                    <!-- Product Details Review -->
                    <div class="product-descripton-review">

                        <ul class="nav" id="product-description-review" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="product-description-tab" data-toggle="tab" href="#product-description" role="tab" aria-controls="product-description" aria-selected="true">Description</a>
                            </li>
{#                            <li class="nav-item">#}
{#                                <a class="nav-link" id="product-reviews-tab" data-toggle="tab" href="#product-reviews" role="tab" aria-controls="product-reviews" aria-selected="false">Reviews (1)</a>#}
{#                            </li>#}
                        </ul>

                        <div class="tab-content" id="product-description-review-content">
                            <div class="tab-pane fade show active" id="product-description" role="tabpanel" aria-labelledby="product-description-tab">
                                <div class="product-description">
                                <p>{{ goods.glong_details }}</p>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="product-reviews" role="tabpanel" aria-labelledby="product-reviews-tab">
                                <div class="product-review">
                                    <div class="commentlist">
                                        <h6>1 REVIEW FOR AENEAN EU TRISTIQUE</h6>
                                        <div class="single-comment">
                                            <div class="single-comment-thumb">
                                                <img src="img/author-image/author-image-1.png" alt="hastech logo">
                                            </div>
                                            <div class="single-comment-content">
                                                <div class="single-comment-content-top">
                                                    <h6>ADMIN – February 17, 2015</h6>
                                                    <div class="ratting-box">
                                                        <span class="active"><i class="fa fa-star"></i></span>
                                                        <span class="active"><i class="fa fa-star"></i></span>
                                                        <span class="active"><i class="fa fa-star"></i></span>
                                                        <span class="active"><i class="fa fa-star"></i></span>
                                                        <span><i class="fa fa-star"></i></span>
                                                    </div>
                                                </div>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam fringilla augue nec est tristique auctor. Donec non est at libero vulputate rutrum.</p>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="commentbox mt-5">
                                        <h6>ADD A REVIEW</h6>
                                        <form action="#" class="sn-form">
                                            <div class="sn-form-inner">
												<div class="single-input">
													<label>Your Rating</label>
													<div class="ratting-box hover-action">
														<span class="active"><i class="fa fa-star"></i></span>
														<span class="active"><i class="fa fa-star"></i></span>
														<span class="active"><i class="fa fa-star"></i></span>
														<span class="active"><i class="fa fa-star"></i></span>
														<span><i class="fa fa-star"></i></span>
													</div>
												</div>
												<div class="single-input">
													<label for="new-review-textbox">Your Review</label>
													<textarea id="new-review-textbox" cols="30" rows="5"></textarea>
												</div>
												<div class="single-input">
													<label for="new-review-name">Name*</label>
													<input type="text" id="new-review-name">
												</div>
												<div class="single-input">
													<label for="new-review-email">Email*</label>
													<input type="email" id="new-review-email">
												</div>
												<div class="single-input">
													<button class="sn-button sn-button-dark" type="submit"><span>Submit</span></button>
												</div>
                                            </div>
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                    <!--// Product Details Review -->

                </div>
                                        
            </div>
            <!--// Product Page Wrapper -->
        </main>
    {% endblock %}